//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameObjectContainerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameObjectContainer), typeof(UnityEngine.MonoBehaviour));
        L.RegFunction("Get", Get);
        L.RegFunction("GetAll", GetAll);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int Get(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
            GameObjectContainer obj = (GameObjectContainer)ToLua.CheckObject(L, 1, typeof(GameObjectContainer));
            int arg0 = LuaDLL.luaL_checkinteger(L, 2);
            UnityEngine.GameObject o = obj.Get(arg0);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int GetAll(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 1);
            GameObjectContainer obj = (GameObjectContainer)ToLua.CheckObject(L, 1, typeof(GameObjectContainer));
            LuaDLL.lua_newtable(L);
            if (obj.objectArray != null)
            {
                for (int i = 0; i < obj.objectArray.Length; i++)
                {
                    GameObjectIndex widget = obj.objectArray[i];
                    ToLua.Push(L, widget.id);
                    ToLua.Push(L, widget.gameObject);
                    LuaDLL.lua_settable(L, -3);
                }
            }
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }
}

