//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ShotHelperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ShotHelper), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Capture", Capture);
		L.RegFunction("CaptureCamera", CaptureCamera);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Capture(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ShotHelper obj = (ShotHelper)ToLua.CheckObject(L, 1, typeof(ShotHelper));
			UnityEngine.Camera arg0 = (UnityEngine.Camera)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Camera));
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.Capture(arg0, arg1);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CaptureCamera(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ShotHelper obj = (ShotHelper)ToLua.CheckObject(L, 1, typeof(ShotHelper));
			UnityEngine.Camera arg0 = (UnityEngine.Camera)ToLua.CheckUnityObject(L, 2, typeof(UnityEngine.Camera));
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			System.Collections.IEnumerator o = obj.CaptureCamera(arg0, arg1);
			ToLua.Push(L, o);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

