//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BuiltInWebView.
/// </summary>
public class BuiltInWebView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/BuiltInWebModule/BuiltInWebView.prefab";
	public UISprite subview_UISprite;
	public UIButton CloseBtn_UIButton;
	public UIButton GoBackBtn_UIButton;
	public UIButton GoForwardBtn_UIButton;
	public UIButton RefreshBtn_UIButton;
	public GameObject Bottom;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;        
		subview_UISprite = root.Find("Content/subview").GetComponent<UISprite>();
		CloseBtn_UIButton = root.Find("Content/Bottom/CloseBtn").GetComponent<UIButton>();
		GoBackBtn_UIButton = root.Find("Content/Bottom/GoBackBtn").GetComponent<UIButton>();
		GoForwardBtn_UIButton = root.Find("Content/Bottom/GoForwardBtn").GetComponent<UIButton>();
		RefreshBtn_UIButton = root.Find("Content/Bottom/RefreshBtn").GetComponent<UIButton>();
		Bottom = root.Find("Content/Bottom").gameObject;
	}
}
