CWelfareView = require "logic.welfare.CWelfareView"
CWelfareCtrl = require "logic.welfare.CWelfareCtrl"
CWelfareBigProfitPart = require "logic.welfare.CWelfareBigProfitPart"
CWelfareLuckyPresentPart = require "logic.welfare.CWelfareLuckyPresentPart"
CWelfareYuanbaoPart = require "logic.welfare.CWelfareYuanbaoPart"
CWelfareExchangePart = require "logic.welfare.CWelfareExchangePart"
-- CWelfareFirstChargePart = require "logic.welfare.CWelfareFirstChargePart"
CWelfareSecondChargePart = require "logic.welfare.CWelfareSecondChargePart"
CRebateExplainPart = require "logic.welfare.CRebateExplainPart"
CWelfareCollectPart = require "logic.welfare.CWelfareCollectPart"
CWelfareLotteryPart = require "logic.welfare.CWelfareLotteryPart"
CWelfareReturnGiftPart = require "logic.welfare.CWelfareReturnGiftPart"
CWelfareEightLoginPart = require "logic.welfare.CWelfareEightLoginPart"
CYoukaLoginView = require "logic.welfare.CYoukaLoginView"
CWelfareGradePushView = require "logic.welfare.CWelfareGradePushView"
--在线豪礼
COnlineGiftPage = require "logic.welfare.COnlineGiftPage"
COnlineGiftCtrl = require "logic.welfare.COnlineGiftCtrl"
--战力礼包
CWelfareFightGiftPart = require "logic.welfare.CWelfareFightGiftPart"
CFightGriftBox = require "logic.welfare.CFightGriftBox"
CBigProfitCtrl = require "logic.welfare.CBigProfitCtrl"
--首充
CFirstPayCtrl = require "logic.welfare.firstPayV2.CFirstPayCtrl"
CFirstPayPage = require "logic.welfare.firstPayV2.CFirstPayPage"
CFirstPayBox = require "logic.welfare.firstPayV2.CFirstPayBox"
--经验找回
CExpRecycleCtrl = require "logic.welfare.expRecycle.CExpRecycleCtrl"
CExpRecyclePage = require "logic.welfare.expRecycle.CExpRecyclePage"