//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameEventHandlerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameEventHandler), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetClickCallback", SetClickCallback);
		L.RegFunction("SetApplicationPauseCallback", SetApplicationPauseCallback);
		L.RegFunction("SetApplicationFocusCallback", SetApplicationFocusCallback);
		L.RegFunction("SetApplicationQuitCallback", SetApplicationQuitCallback);
		L.RegFunction("CallApplicationQuit", CallApplicationQuit);
        L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int get_Instance(IntPtr L)
    {
        try
        {
            ToLua.Push(L, GameEventHandler.Instance);
            return 1;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
    }

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetClickCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameEventHandler obj = (GameEventHandler)ToLua.CheckObject(L, 1, typeof(GameEventHandler));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetClickCallback(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}


	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetApplicationPauseCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameEventHandler obj = (GameEventHandler)ToLua.CheckObject(L, 1, typeof(GameEventHandler));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetApplicationPauseCallback(arg0);
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
    static int SetApplicationFocusCallback(IntPtr L)
    {
        try
        {
            ToLua.CheckArgsCount(L, 2);
            GameEventHandler obj = (GameEventHandler)ToLua.CheckObject(L, 1, typeof(GameEventHandler));
            LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
            obj.SetApplicationFocusCallback(arg0);
            return 0;
        }
        catch (Exception e)
        {
            return LuaDLL.toluaL_exception(L, e);
        }
	}
	
	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetApplicationQuitCallback(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			GameEventHandler obj = (GameEventHandler)ToLua.CheckObject(L, 1, typeof(GameEventHandler));
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetApplicationQuitCallback(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
	
	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CallApplicationQuit(IntPtr L)
	{
		try
		{
			GameEventHandler.Instance.CallApplicationQuit();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

