CWenShiCtrl = require "logic.horsewenshi.CWenShiCtrl"
CHorseWenShiMainView = require "logic.horsewenshi.CHorseWenShiMainView"
CWenShiFusionPart = require "logic.horsewenshi.CWenShiFusionPart"
CWenShiWashPart = require "logic.horsewenshi.CWenShiWashPart"
CWenShiAddView = require "logic.horsewenshi.CWenShiAddView"
CWenShiFusionSuccessView = require "logic.horsewenshi.CWenShiFusionSuccessView"
CWenShiAttrItem = require "logic.horsewenshi.CWenShiAttrItem"
CWenShiSkillTipView = require "logic.horsewenshi.CWenShiSkillTipView"