CAssembleTreasureView = require "logic.assembletreasure.CAssembleTreasureView"
CAssembleTreasureCtrl = require "logic.assembletreasure.CAssembleTreasureCtrl"
CAssemBleTreasureRankView = require "logic.assembletreasure.CAssemBleTreasureRankView"
CAssemBleTreasureScoreView = require "logic.assembletreasure.CAssemBleTreasureScoreView"
CAssemBleTreasureTipView = require "logic.assembletreasure.CAssemBleTreasureTipView"
