CSummonChangeNameView = require "logic.summon.CSummonChangeNameView"
CSummonPotentialView = require "logic.summon.CSummonPotentialView"
CSummonAddPointSchemeView = require "logic.summon.CSummonAddPointSchemeView"
SummonFreeSureView = require "logic.summon.SummonFreeSureView"
CSummonSkillItemTipsView = require "logic.summon.CSummonSkillItemTipsView"
CSummonComOutView = require "logic.summon.CSummonComOutView"
CSummonAddExpView = require "logic.summon.CSummonAddExpView"
CSummonAddLifeView = require "logic.summon.CSummonAddLifeView"
-- old
-- CSummonAdjustPart = require "logic.summon.CSummonAdjustPart"
CSummonWashPointView = require "logic.summon.CSummonWashPointView"
-- CSummonLAttrPageBox = require "logic.summon.CSummonLAttrPageBox"
-- CSummonCulturePageBox = require "logic.summon.CSummonCulturePageBox"
-- CSummonCompoundPageBox = require "logic.summon.CSummonCompoundPageBox"
-- CSummonRStudySkillPageBox = require "logic.summon.CSummonRStudySkillPageBox"
-- CSummonDetailInfoPart = require "logic.summon.CSummonDetailInfoPart"
-- CSummonPropertyPart = require "logic.summon.CSummonPropertyPart"
CSummonComposePreView = require "logic.summon.CSummonComposePreView"

SummonDataTool = require "logic.summon.SummonDataTool"
CSummonCtrl = require "logic.summon.CSummonCtrl"

CSummonAptiBox = require "logic.summon.CSummonAptiBox"
CSummonListBox = require "logic.summon.CSummonListBox"
CSummonItemBox = require "logic.summon.CSummonItemBox"
CSummonViewBox = require "logic.summon.CSummonViewBox"
CSummonViewEquipBox = require "logic.summon.CSummonViewEquipBox"
CSummonMainView = require "logic.summon.CSummonMainView"
---------------- property ---------------
CSummonLAttrPart = require "logic.summon.CSummonLAttrPart"
CSummonRAttrPart = require "logic.summon.CSummonRAttrPart"
CSummonAddPointPart = require "logic.summon.CSummonAddPointPart"
CSummonPropertyPage = require "logic.summon.CSummonPropertyPage"
------------- skill ------------------
CSummonSkillItemBox = require "logic.summon.CSummonSkillItemBox"
CSummonSkillBox = require "logic.summon.CSummonSkillBox"
------------- book --------------------
CSummonBookAptiBox = require "logic.summon.CSummonBookAptiBox"
CSummonBookInfoBox = require "logic.summon.CSummonBookInfoBox"
CSummonBookListBox = require "logic.summon.CSummonBookListBox"
CSummonGetWayBox = require "logic.summon.CSummonGetWayBox"
CSummonBookItemBox = require "logic.summon.CSummonBookItemBox"
CSummonBookPage = require "logic.summon.CSummonBookPage"
CSummonSpcGetWayBox = require "logic.summon.CSummonSpcGetWayBox"
---------------- Adjust ------------------
CSummonAdjustPage = require "logic.summon.CSummonAdjustPage"
CSummonWashPart = require "logic.summon.CSummonWashPart"
CSummonAdjustViewPart = require "logic.summon.CSummonAdjustViewPart"
CSummonStudyPart = require "logic.summon.CSummonStudyPart"
CSummonStudyItemView = require "logic.summon.CSummonStudyItemView"
CSummonStudyItemBox = require "logic.summon.CSummonStudyItemBox"
CSummonCompoundPart = require "logic.summon.CSummonCompoundPart"
CSummonCompoundMatPart = require "logic.summon.CSummonCompoundMatPart"
CSummonCompoundItemBox = require "logic.summon.CSummonCompoundItemBox"
CSummonCompoundSelView = require "logic.summon.CSummonCompoundSelView"
CSummonSpcComposeView = require "logic.summon.CSummonSpcComposeView"
CSummonCulturePart = require "logic.summon.CSummonCulturePart"
CSummonCultureAptiBox = require "logic.summon.CSummonCultureAptiBox"
---------------- Link ------------------
CSummonLinkView = require "logic.summon.CSummonLinkView"
CSummonLinkRPart = require "logic.summon.CSummonLinkRPart"
------------------ equip ----------------
CSummonEquipSelView = require "logic.summon.CSummonEquipSelView"
CSummonEquipEditView = require "logic.summon.CSummonEquipEditView"
CSummonEquipBagPart = require "logic.summon.CSummonEquipBagPart"
CSummonEquipResetBox = require "logic.summon.CSummonEquipResetBox"
CSummonEquipComposeBox = require "logic.summon.CSummonEquipComposeBox"
CSummonEquipTipBox = require "logic.summon.CSummonEquipTipBox"
--- 宠物仓库
CSummonWarehouseView = require "logic.summon.CSummonWarehouseView"
CSummonWarehouseBox  = require "logic.summon.CSummonWarehouseBox"
-- 洗练保底确认
CSummonWashComfirmView = require "logic.summon.CSummonWashComfirmView"
--------------------- advance level -------------------
CSummonAdvanceView = require "logic.summon.CSummonAdvanceView"
CSummonAdvAptiBox = require "logic.summon.CSummonAdvAptiBox"
CSummonBookAdvAptiBox = require "logic.summon.CSummonBookAdvAptiBox"