CTitleView = require "logic.title.CTitleView"
CTitleDescItem = require "logic.title.CTitleDescItem"
CNormalTitleItem = require "logic.title.CNormalTitleItem"
CSpecialTitleItem = require "logic.title.CSpecialTitleItem"
CTitleLinkView = require "logic.title.CTitleLinkView"
CTitleCtrl = require "logic.title.CTitleCtrl"