//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RequestLoadingTipPrefab.
/// </summary>
public partial class RequestLoadingTipPrefab : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/CommonUIModule/RequestLoadingTipPrefab.prefab";
	public Transform LoadingGroup_Transform;
	public UILabel TipLabel_UILabel;
	public UISprite CircleSprite_UISprite;
	public UISprite BgSprite_UISprite;
	public BoxCollider BlackSprite_BoxCollider;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		LoadingGroup_Transform = root.Find("LoadingGroup");
		TipLabel_UILabel = root.Find("LoadingGroup/TipLabel").GetComponent<UILabel>();
		CircleSprite_UISprite = root.Find("LoadingGroup/CircleSprite").GetComponent<UISprite>();
		BgSprite_UISprite = root.Find("LoadingGroup/BgSprite").GetComponent<UISprite>();
		BlackSprite_BoxCollider = root.Find("BlackSprite").GetComponent<BoxCollider>();
	}
}
