//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GameLauncherView.
/// </summary>
public class GameLauncherView : MonoBehaviour
{
    public UITexture LogoTexture_UITexture;
    public UITexture InitBgTexture_UITexture;
    public UILabel tipsLbl;
	public UILabel VersionLabel_UILabel;

	public Transform DownloadObj;
	public UIButton UpdateTip_OkBtn;
	
	public Transform UpdateTipObj;
	public UIButton UpdateAll_OkBtn;
	
	public Transform UpdateInfoObj;
	public UIButton UpdateRes_CloseBtn;
	public UILabel UpdateRes_CurVersion;
	public UILabel UpdateRes_TargetVersion;
	public UILabel UpdateRes_TotleSize;
	public UIButton UpdateRes_OkBtn;
	public UILabel UpdateRes_OkLabel;
	
	public Transform UpdateSlider;
	public UISlider UpdateSlider_Slider;
	public UILabel UpdateSlider_NetType;
	public UILabel UpdateSlider_CurVersion;
	public UILabel UpdateSlider_UpdatePro;
	public UILabel UpdateSlider_Proportion;

    public void Setup(Transform root)
    {
		LogoTexture_UITexture = root.Find("LogoTexture").GetComponent<UITexture>();
        InitBgTexture_UITexture = root.Find("InitBgTexture").GetComponent<UITexture>();
        tipsLbl = root.Find("tipsLbl").GetComponent<UILabel>();
		VersionLabel_UILabel = root.Find("RightAnchor/VersionLabel").GetComponent<UILabel>();
		DownloadObj = root.Find("UpdateTip").GetComponent<Transform>();
		UpdateTip_OkBtn = root.Find ("UpdateTip/OkBtn").GetComponent<UIButton>();
		
		UpdateTipObj = root.Find("UpdateAll").GetComponent<Transform>();
		UpdateAll_OkBtn = root.Find ("UpdateAll/OkBtn").GetComponent<UIButton>();
		
		UpdateInfoObj = root.Find("UpdateRes").GetComponent<Transform>();
		UpdateRes_CloseBtn = root.Find ("UpdateRes/CloseBtn").GetComponent<UIButton>();
		UpdateRes_CurVersion = root.Find ("UpdateRes/CurVersion").GetComponent<UILabel>();
		UpdateRes_TargetVersion = root.Find ("UpdateRes/TargetVersion").GetComponent<UILabel>();
		UpdateRes_TotleSize = root.Find ("UpdateRes/TotleSize").GetComponent<UILabel>();
		UpdateRes_OkBtn = root.Find ("UpdateRes/OkBtn").GetComponent<UIButton>();
		UpdateRes_OkLabel = root.Find ("UpdateRes/OkBtn/Label").GetComponent<UILabel>();
		
		UpdateSlider = root.Find("UpdateSlider").GetComponent<Transform>();
		UpdateSlider_Slider = root.Find("UpdateSlider/Slider").GetComponent<UISlider>();
		UpdateSlider_NetType = root.Find ("UpdateSlider/NetType").GetComponent<UILabel>();
		UpdateSlider_CurVersion = root.Find ("UpdateSlider/CurVersion").GetComponent<UILabel>();
		UpdateSlider_UpdatePro = root.Find ("UpdateSlider/UpdatePro").GetComponent<UILabel>();
		UpdateSlider_Proportion = root.Find ("UpdateSlider/Proportion").GetComponent<UILabel>();
    }
}
