--协议锁项
module(...)

LockProtoList = {
	-- [===[
	["login"] = {
		-- ["C2GSLoginAccount"] = {Lock = true, Tip = "登录账号中，请稍候...", Style = 0},
		-- ["C2GSLoginRole"] = {Lock = true, Tip = "登录角色中，请稍候..."},
		["C2GSCreateRole"] = {Lock = true, Tip = "创建角色中，请稍候..."},
		["C2GSQuitLoginQueue"] = {Lock = true},
		["C2GSGetLoginWaitInfo"] = {Lock = true},
		["C2GSReLoginRole"] = {Lock = true, Tip = "重连中...", Style = 1},
	},
	["item"] = {
		-- ["C2GSItemUse"] = {Lock = true, Tip = "", Delay = 0.5, Count = 1},
		["C2GSItemListUse"] = {Lock = true},
		["C2GSItemUse"] = {Lock = true},
		["C2GSItemInfo"] = {Lock = true},
		["C2GSItemMove"] = {Lock = true},
		["C2GSAddItemExtendSize"] = {Lock = true},
		["C2GSDeComposeItem"] = {Lock = true},
		["C2GSComposeItem"] = {Lock = true},
		["C2GSMakeEquip"] = {Lock = true},
		--["C2GSMakeEquipInfo"] = {Lock = true},
		["C2GSFixEquip"] = {Lock = true},
		["C2GSEquipStrength"] = {Lock = true},
		["C2GSWashEquip"] = {Lock = true},
		--["C2GSWashEquipInfo"] = {Lock = true},
		["C2GSUseWashEquip"] = {Lock = true},
		["C2GSMergeShenHun"] = {Lock = true},
		["C2GSUseShenHun"] = {Lock = true},
		["C2GSCompoundItem"] = {Lock = true},
		["C2GSItemArrage"] = {Lock = true},
		["C2GSRecycleItem"] = {Lock = true},

		--["C2GSStrengthInfo"] = {Lock = true},
		["C2GSFixAllEquips"] = {Lock = true},
		["C2GSEquipBreak"] = {Lock = true},
		["C2GSDeComposeItemList"] = {Lock = true},
		["C2GSRecFuHunPointReward"] = {Lock = true},
		-- ["C2GSGetFuHunCost"] = {Lock = true},
		["C2GSSummonEquipResetSkill"] = {Lock = true},
		["C2GSSummonEquipCombine"] = {Lock = true},

	},
	["auction"] = {
		["C2GSAuctionUpItem"] = {Lock = true},
		["C2GSAuctionUpSummon"] = {Lock = true},
		["C2GSAuctionGetCash"] = {Lock = true},
		["C2GSAuctionBid"] = {Lock = true},
		["C2GSAuctionReward"] = {Lock = true},
		["C2GSAuctionGetAllCash"] = {Lock = true},
		["C2GSGetReturnMoney"] = {Lock = true},
	},
	["other"] = {
		["C2GSRequestPay"] = {Lock = true},
		["C2GSUseRedeemCode"] = {Lock = true}
	},
	["huodong"] = {
		["C2GSSignInMainInfo"] = {Lock = true, Tip = "加载签到数据中，请稍候..."}
	},
	["player"] = {
		["C2GSGetPromote"] = {Lock = true, Tip = "指引信息加载中，请稍候..."},
		["C2GSSelectPointPlan"] = {Lock = true},
		["C2GSAddPoint"] = {Lock = true},
		["C2GSWashAllPoint"] = {Lock = true},
		["C2GSGetPlayerInfo"] = {Lock = true},
		--["C2GSGetSecondProp"] = {Lock = true},
		["C2GSPlayerItemInfo"] = {Lock = true},
		["C2GSPlayerSummonInfo"] = {Lock = true},
		["C2GSNameCardInfo"] = {Lock = true},
		["C2GSUpvotePlayer"] = {Lock = true},
		["C2GSPlayerUpvoteInfo"] = {Lock = true},
		["C2GSRename"] = {Lock = true},
		["C2GSHidePosition"] = {Lock = true},
		["C2GSUpvoteReward"] = {Lock = true},
		["C2GSObserverWar"] = {Lock = true},
		["C2GSPlayerRanSe"] = {Lock = true},
		["C2GSObserverWar"] = {Lock = true},
		["C2GSSysConfig"] = {Lock = true},
		["C2GSRewardGradeGift"] = {Lock = true},
		["C2GSPlayerPartnerInfo"] = {Lock = true},
		["C2GSLeaveObserverWar"] = {Lock = true},
		["C2GSGetScore"] = {Lock = true},
		["C2GSRewardPreopenGift"] = {Lock = true},
		["C2GSSZRanse"] = {Lock = true},
		["C2GSOpenShiZhuang"] = {Lock = true},
		["C2GSSetSZ"] = {Lock = true},
		["C2GSSetSZColor"] = {Lock = true},
		["C2GSGetAllSZInfo"] = {Lock = true},
	},
	["org"] = {
		["C2GSOrgMainInfo"] = {Lock = true, Tip = "帮派信息加载中，请稍候..."}
	},
	["mail"] = {
		["C2GSOpenMail"] = {Lock = true, Tip = "邮件信息加载中，请稍候..."}
	},
	["scene"] = {
		["C2GSTransfer"] = {Lock = true},
		["C2GSClickWorldMap"] = {Lock = true},
		["C2GSClickTrapMineMap"] = {Lock = true}
	},
	["task"] = {
		["C2GSClickTask"] = {Lock = true},
		--["C2GSTaskEvent"] = {Lock = true},
		["C2GSCommitTask"] = {Lock = true},
		["C2GSAbandonTask"] = {Lock = true},
		["C2GSStepTask"] = {Lock = true},
		["C2GSAcceptTask"] = {Lock = true},
		["C2GSYibaoSeekHelp"] = {Lock = true},
		["C2GSYibaoGiveHelp"] = {Lock = true},
		["C2GSYibaoHelpSubmit"] = {Lock = true},
		["C2GSYibaoAccept"] = {Lock = true},
		["C2GSRewardStoryChapter"] = {Lock = true},
		["C2GSRewardEverydayTask"] = {Lock = true},
		["C2GSLingxiUseSeed"] = {Lock = true},
		["C2GSLingxiQuestionAnswer"] = {Lock = true},
	},
	["npc"] = {
		--["C2GSClickNpc"] = {Lock = true},
		["C2GSNpcRespond"] = {Lock = true},
		["C2GSFindPathToNpc"] = {Lock = true},
	},
	["openui"] = {
		["C2GSOpenScheduleUI"] = {Lock = true},
		["C2GSWeekSchedule"] = {Lock = true},
		["C2GSScheduleReward"] = {Lock = true},

		["C2GSOpenInterface"] = {Lock = true},
		["C2GSCloseInterface"] = {Lock = true},
		["C2GSOpenFBComfirm"] = {Lock = true},
		["C2GSUseAdvanceMap"] = {Lock = true},
		["C2GSFindHDNpc"] = {Lock = true},
		["C2GSFindGlobalNpc"] = {Lock = true},
		["C2GSExchangeItem"] = {Lock = true},
		["C2GSExchangeCash"] = {Lock = true},
	},
	["warehouse"] = {
		["C2GSSwitchWareHouse"] = {Lock = true},
		["C2GSRenameWareHouse"] = {Lock = true},
		["C2GSWareHouseWithStore"] = {Lock = true},

		["C2GSWareHouseWithDraw"] = {Lock = true},
		["C2GSWareHouseArrange"] = {Lock = true},
	},
	["team"] = {
		["C2GSCreateTeam"] = {Lock = true},
		["C2GSTeamInfo"] = {Lock = true},
		["C2GSApplyTeam"] = {Lock = true},
		["C2GSTeamApplyInfo"] = {Lock = true},
		["C2GSApplyTeamPass"] = {Lock = true},
		["C2GSClearApply"] = {Lock = true},
		["C2GSInviteTeam"] = {Lock = true},
		["C2GSInvitePass"] = {Lock = true},
		["C2GSClearInvite"] = {Lock = true},
		["C2GSShortLeave"] = {Lock = true},
		["C2GSLeaveTeam"] = {Lock = true},
		["C2GSKickOutTeam"] = {Lock = true},
		["C2GSBackTeam"] = {Lock = true},
		["C2GSTeamSummon"] = {Lock = true},
		["C2GSApplyLeader"] = {Lock = true},
		["C2GSSetLeader"] = {Lock = true},
		["C2GSTeamInviteInfo"] = {Lock = true},
		["C2GSTeamAutoMatch"] = {Lock = true},
		["C2GSTeamCancelAutoMatch"] = {Lock = true},
		["C2GSPlayerAutoMatch"] = {Lock = true},
		["C2GSPlayerCancelAutoMatch"] = {Lock = true},
		-- ["C2GSGetTargetTeamInfo"] = {Lock = true},
		["C2GSCancelApply"] = {Lock = true},
		["C2GSSetAppointMem"] = {Lock = true},
		["C2GSSetTeamWarCmd"] = {Lock = true},
		["C2GSAddTeamWarCmd"] = {Lock = true},
	},
	["chat"] = {
		["C2GSChat"] = {Lock = true},
		["C2GSChuanYin"] = {Lock = true},
	},
	["summon"] = {
		["C2GSWashSummon"] = {Lock = true},
		["C2GSStickSkill"] = {Lock = true},
		["C2GSSummonChangeName"] = {Lock = true},
		["C2GSSummonSetFight"] = {Lock = true},
		["C2GSReleaseSummon"] = {Lock = true},
		["C2GSSummonAssignPoint"] = {Lock = true},
		["C2GSSummonAutoAssignScheme"] = {Lock = true},
		["C2GSSummonOpenAutoAssign"] = {Lock = true},
		["C2GSSummonRequestAuto"] = {Lock = true},
		["C2GSCombineSummon"] = {Lock = true},
		["C2GSSummonFollow"] = {Lock = true},
		["C2GSSummonRestPointUI"] = {Lock = true},
		--["C2GSGetSummonSecProp"] = {Lock = true},
		["C2GSGetSummonRanse"] = {Lock = true},
		["C2GSCombineSummonLead"] = {Lock = true},
		["C2GSSummonRanse"] = {Lock = true},
		["C2GSSummonBindSKill"] = {Lock = true},
		["C2GSShenShouExchange"] = {Lock = true},
		["C2GSEquipSummon"] = {Lock = true},
	},
	["skill"] = {
		["C2GSFastLearnSkill"] = {Lock = true},
		["C2GSSetCultivateSkill"] = {Lock = true},
		["C2GSResetActiveSchool"] = {Lock = true},
	},
	["store"] = {
		["C2GSExchangeGold"] = {Lock = true},
		["C2GSExchangeSilver"] = {Lock = true},
		["C2GSNpcStoreBuy"] = {Lock = true, Tip = "游戏商店购买物品中，请稍候...", ResumeDelay = 10},
		["C2GSFastBuyItem"] = {Lock = true},
	},
	["state"] = {
		["C2GSClickState"] = {Lock = true},
		["C2GSAddBaoShi"] = {Lock = true},
	},
	["mail"] = {
		["C2GSOpenMail"] = {Lock = true},
		["C2GSAcceptAttach"] = {Lock = true},
		["C2GSAcceptAllAttach"] = {Lock = true},
		["C2GSDeleteMail"] = {Lock = true},
		["C2GSDeleteAllMail"] = {Lock = true},
	},
	["test"] = {

	},
	["org"] = {
		["C2GSOrgList"] = {Lock = true},
		["C2GSSearchOrg"] = {Lock = true},
		["C2GSCreateOrg"] = {Lock = true},
		["C2GSApplyJoinOrg"] = {Lock = true},
		["C2GSMultiApplyJoinOrg"] = {Lock = true},
		["C2GSReadyOrgList"] = {Lock = true},
		["C2GSRespondOrg"] = {Lock = true},
		["C2GSMultiRespondOrg"] = {Lock = true},
		["C2GSOrgMainInfo"] = {Lock = true},
		["C2GSOrgMemberList"] = {Lock = true},
		["C2GSOrgApplyJoinList"] = {Lock = true},
		["C2GSOrgDealApply"] = {Lock = true},
		["C2GSAgreeAllApply"] = {Lock = true},
		["C2GSOrgSetPosition"] = {Lock = true},
		["C2GSLeaveOrg"] = {Lock = true},
		["C2GSRequestOrgAim"] = {Lock = true},
		["C2GSReadyOrgInfo"] = {Lock = true},
		["C2GSSpreadOrg"] = {Lock = true},
		["C2GSUpdateAim"] = {Lock = true},
		["C2GSKickMember"] = {Lock = true},
		["C2GSApplyOrgLeader"] = {Lock = true},
		["C2GSVoteOrgLeader"] = {Lock = true},
		["C2GSInvited2Org"] = {Lock = true},
		["C2GSDealInvited2Org"] = {Lock = true},
		["C2GSClearApplyAndRespond"] = {Lock = true},
		["C2GSGetOnlineMember"] = {Lock = true},
		["C2GSGetBuildInfo"] = {Lock = true},
		["C2GSUpGradeBuild"] = {Lock = true},
		["C2GSQuickBuild"] = {Lock = true},
		["C2GSGetShopInfo"] = {Lock = true},
		["C2GSBuyItem"] = {Lock = true},
		["C2GSGetBoonInfo"] = {Lock = true},
		["C2GSOrgSign"] = {Lock = true},
		["C2GSReceiveBonus"] = {Lock = true},
		["C2GSReceivePosBonus"] = {Lock = true},
		["C2GSGetAchieveInfo"] = {Lock = true},
		["C2GSReceiveAchieve"] = {Lock = true},
		["C2GSEnterOrgScene"] = {Lock = true},
		["C2GSNextPageLog"] = {Lock = true},
		["C2GSChatBan"] = {Lock = true},
		["C2GSClickOrgBuild"] = {Lock = true},
		["C2GSClearApplyList"] = {Lock = true},
		["C2GSOrgPrestigeInfo"] = {Lock = true},
		["C2GSSetAutoJoin"] = {Lock = true},
		["C2GSSendOrgMail"] = {Lock = true},		
	},
	["partner"] = {
		["C2GSRecruit"] = {Lock = true},
		["C2GSUpgradeQuality"] = {Lock = true},
		["C2GSUpperGradeLimit"] = {Lock = true},
		["C2GSUseUpgradeProp"] = {Lock = true},
		["C2GSSwapProtectSkill"] = {Lock = true},
		["C2GSUpgradeSkill"] = {Lock = true},
		["C2GSWieldEquip"] = {Lock = true},
		["C2GSSetPartnerPosInfo"] = {Lock = true},
		["C2GSGetAllLineupInfo"] = {Lock = true},
		["C2GSSetCurrLineup"] = {Lock = true},		
		["C2GSUpgradePartnerEquip"] = {Lock = true},		
		["C2GSStrengthPartnerEquip"] = {Lock = true},		
	},
	["friend"] = {
		--["C2GSQueryFriendProfile"] = {Lock = true},
		["C2GSChatTo"] = {Lock = true},
		-- ["C2GSAckChatFrom"] = {Lock = true},
		["C2GSApplyAddFriend"] = {Lock = true},
		["C2GSApplyDelFriend"] = {Lock = true},
		["C2GSFindFriend"] = {Lock = true},
		["C2GSFriendShield"] = {Lock = true},
		["C2GSFriendUnshield"] = {Lock = true},
		["C2GSSendFlower"] = {Lock = true},
		["C2GSOpenSendFlowerUI"] = {Lock = true},
	},
	["newbieguide"] = {
		-- ["C2GSUpdateNewbieGuideInfo"] = {Lock = true},
		["C2GSNewSysOpenNotified"] = {Lock = true},
		["C2GSSelectNewbieSummon"] = {Lock = true},
		--["C2GSGetNewbieGuildInfo"] = {Lock = true},
	},
	["rank"] = {
		-- ["C2GSGetRankInfo"] = {Lock = true},
		["C2GSGetRankTop3"] = {Lock = true},
		-- 点赞信息
		-- ["C2GSGetUpvoteAmount"] = {Lock = true},
		["C2GSGetRankSumInfo"] = {Lock = true},
	},
	["title"] = {
		["C2GSUseTitle"] = {Lock = true},
	},
	["formation"] = {
		-- ["C2GSAllFormationInfo"] = {Lock = true},
		["C2GSSingleFormationInfo"] = {Lock = true},
		["C2GSSetPlayerPosInfo"] = {Lock = true},
	},
	["jjc"] = {
		["C2GSOpenJJCMainUI"] = {Lock = true},
		["C2GSSetJJCFormation"] = {Lock = true},
		["C2GSSetJJCSummon"] = {Lock = true},
		["C2GSSetJJCPartner"] = {Lock = true},
		["C2GSQueryJJCTargetLineup"] = {Lock = true},
		["C2GSJJCStartFight"] = {Lock = true},
		["C2GSJJCGetFightLog"] = {Lock = true},
		["C2GSJJCBuyFightTimes"] = {Lock = true},
		["C2GSJJCClearCD"] = {Lock = true},
		["C2GSOpenChallengeUI"] = {Lock = true},
		["C2GSChooseChallenge"] = {Lock = true},
		["C2GSSetChallengeFormation"] = {Lock = true},
		["C2GSSetChallengeSummon"] = {Lock = true},
		["C2GSSetChallengeFighter"] = {Lock = true},
		["C2GSResetChallengeTarget"] = {Lock = true},
		["C2GSStartChallenge"] = {Lock = true},
		["C2GSGetChallengeReward"] = {Lock = true},
		["C2GSChallengeTargetLineup"] = {Lock = true},
	},

	["touxian"] = {
		["C2GSUpgradeTouxian"] = {Lock = true},
	},
	["guild"] = {
		["C2GSOpenGuild"] = {Lock = true, Tip= "加载商会数据中，请稍候..."},
		["C2GSBuyGuildItem"] = {Lock = true, Tip = "购买物品中，请稍候...", ResumeDelay = 10},
		["C2GSSellGuildItem"] = {Lock = true},
		["C2GSGetGuildPrice"] = {Lock = true},
	},
	["stall"] = {
		["C2GSAddSellItem"] = {Lock = true},
		["C2GSAddSellItemList"] = {Lock = true},
		["C2GSAddOverTimeItem"] = {Lock = true},
		["C2GSResetItemPrice"] = {Lock = true},
		["C2GSRemoveSellItem"] = {Lock = true},
		["C2GSWithdrawAllCash"] = {Lock = true},
		["C2GSBuySellItem"] = {Lock = true, Tip = "购买物品中，请稍候...", ResumeDelay = 10},
		["C2GSSellItemDetail"] = {Lock = true},
		-- ["C2GSOpenStalls"] = {Lock = true},
		-- ["C2GSOpenCatalog"] = {Lock = true},
		["C2GSRefreshCatalog"] = {Lock = true},
		["C2GSGetDefaultPrice"] = {Lock = true},
		["C2GSWithdrawOneGrid"] = {Lock = true},
		["C2GSUnlockGrid"] = {Lock = true},
	},
	["huodong"] = {
		["C2GSArenaFight"] = {Lock = true},
		["C2GSArenaViewList"] = {Lock = true},
		["C2GSArenaFightList"] = {Lock = true},
		["C2GSShootCrapOpen"] = {Lock = true},
		["C2GSShootCrapStart"] = {Lock = true},
		["C2GSShootCrapEnd"] = {Lock = true},
		["C2GSDanceStart"] = {Lock = true},
		["C2GSDanceEnd"] = {Lock = true},
		["C2GSDanceInspired"] = {Lock = true},
		["C2GSCampfireAnswer"] = {Lock = true},
		["C2GSCampfireDrink"] = {Lock = true},
		["C2GSCampfireQueryGiftables"] = {Lock = true},
		["C2GSCampfireGiftOut"] = {Lock = true},
		["C2GSSignInDone"] = {Lock = true},
		["C2GSSignInReplenish"] = {Lock = true},
		["C2GSSignInLottery"] = {Lock = true},
		["C2GSSignInMainInfo"] = {Lock = true},
		["C2GSMengzhuOpenPlayerRank"] = {Lock = true},
		["C2GSMengzhuOpenOrgRank"] = {Lock = true},
		["C2GSMengzhuStartPlunder"] = {Lock = true},
		["C2GSMengzhuOpenPlunder"] = {Lock = true},
		["C2GSMengzhuStartFightBoss"] = {Lock = true},
		["C2GSMengzhuMainUI"] = {Lock = true},
		["C2GSCampfireThankGift"] = {Lock = true},
		["C2GSBWRank"] = {Lock = true},
		["C2GSBWMakeTeam"] = {Lock = true},
		["C2GSSchoolPassClickNpc"] = {Lock = true},
		["C2GSDanceAuto"] = {Lock = true},
		["C2GSCampfireDesireQuestion"] = {Lock = true},
		["C2GSOrgTaskRandTask"] = {Lock = true},
		["C2GSOrgTaskResetStar"] = {Lock = true},
		["C2GSOrgTaskReceiveTask"] = {Lock = true},
		["C2GSOrgTaskFindNPC"] = {Lock = true},
		["C2GSBaikeChooseAnswer"] = {Lock = true},
		["C2GSBaikeOpenUI"] = {Lock = true},
		["C2GSBaikeLinkAnswer"] = {Lock = true},
		["C2GSChargeRewardGoldCoinGift"] = {Lock = true},
		["C2GSBaikeGetNextQuestion"] = {Lock = true},
		["C2GSChargeRewardGradeGift"] = {Lock = true},
		["C2GSBottleDetail"] = {Lock = true},
		["C2GSBottleSend"] = {Lock = true},
		["C2GSBaikeWeekRank"] = {Lock = true},
		["C2GSLMLookInfo"] = {Lock = true},
		["C2GSLingxiPaticipate"] = {Lock = true},
		["C2GSRewardFirstPayGift"] = {Lock = true},
		["C2GSRewardWelfareGift"] = {Lock = true},
		["C2GSJoinJYFuben"] = {Lock = true},
		["C2GSRedeemCollectGift"] = {Lock = true},
		["C2GSCaishenStartChoose"] = {Lock = true},
		["C2GSOrgWarOpenTeamUI"] = {Lock = true},
		["C2GSOrgWarStartFight"] = {Lock = true},
		["C2GSOrgWarOpenMatchList"] = {Lock = true},
		["C2GSOrgWarOpenWarScoreUI"] = {Lock = true},
		["C2GSOrgWarTryGotoNpc"] = {Lock = true},
		["C2GSOrgTaskStarReward"] = {Lock = true},
		["C2GSChargeGetDayReward"] = {Lock = true},
		["C2GSTrialGetReward"] = {Lock = true},
		["C2GSTrialOpenUI"] = {Lock = true},
		["C2GSTiralStartFight"] = {Lock = true},
		["C2GSHfdmSelect"] = {Lock = true},
		["C2GSHfdmEnter"] = {Lock = true},
		["C2GSHfdmUseSkill"] = {Lock = true},
		["C2GSChargeCheckBuy"] = {Lock = true},
		["C2GSLingxiStopMatch"] = {Lock = true},
		["C2GSGrowReward"] = {Lock = true},
		["C2GSReturnGoldCoinBuyGift"] = {Lock = true},
		["C2GSReturnGoldCoinGetFreeGift"] = {Lock = true},
		["C2GSReturnGoldCoinGetReturn"] = {Lock = true},
	},
	["redpacket"] = {
		["C2GSSendRP"] = {Lock = true},
		["C2GSRobRP"] = {Lock = true},
		--["C2GSQueryAll"] = {Lock = true},
		["C2GSQueryBasic"] = {Lock = true},
		["C2GSQueryHistory"] = {Lock = true},
		["C2GSUseRPItem"] = {Lock = true},
		["C2GSActiveSendSYS"] = {Lock = true},
	},
	["auction"] = {
		["C2GSOpenAuction"] = {Lock = true},
		["C2GSOpenMyFollows"] = {Lock = true},
		["C2GSOpenMyBidItems"] = {Lock = true},
		["C2GSAuctionUpItem"] = {Lock = true},
		["C2GSAuctionUpSummon"] = {Lock = true},
		["C2GSAuctionDownItem"] = {Lock = true},
		["C2GSAuctionGetCash"] = {Lock = true},
		["C2GSAuctionBid"] = {Lock = true},
		["C2GSSetProxyPrice"] = {Lock = true},
		["C2GSToggleFollow"] = {Lock = true},
		["C2GSShowAuction"] = {Lock = true},
		["C2GSOpenMyAuctions"] = {Lock = true},
		["C2GSCancelProxyPrice"] = {Lock = true},
		["C2GSAuctionGetAllCash"] = {Lock = true},
		["C2GSAuctionReward"] = {Lock = true},
		["C2GSAuctionLog"] = {Lock = true},
		["C2GSGetReturnMoney"] = {Lock = true},
		["C2GSClickLink"] = {Lock = true},
	},
	["ride"] = {
		["C2GSActivateRide"] = {Lock = true},
		["C2GSUseRide"] = {Lock = true},
		["C2GSRandomRideSkill"] = {Lock = true},
		["C2GSLearnRideSkill"] = {Lock = true},
		["C2GSResetRideSkill"] = {Lock = true},
		["C2GSSetRideFly"] = {Lock = true},
		["C2GSGetRideInfo"] = {Lock = true},
	},
	["bulletbarrage"] = {
		["C2GSWarBulletBarrage"] = {Lock = true},
		["C2GSVideoBulletBarrage"] = {Lock = true},
		["C2GSOrgBulletBarrage"] = {Lock = true},
		["C2GSStoryBulletBarrage"] = {Lock = true},
		["C2GSGetStoryBulletBarrage"] = {Lock = true},
	},
	["tempitem"] = {
		["C2GSTranToItemBag"] = {Lock = true},
		["C2GSOpenTempItemUI"] = {Lock = true},	
	},
	["recovery"] = {
		["C2GSRecoveryItem"] = {Lock = true},
		["C2GSRecoverySum"] = {Lock = true},
	},

	["vigor"] = {
		["C2GSOpenVigorChange"] = {Lock = true},
		["C2GSChangeGoldcoinToVigor"] = {Lock = true},
		["C2GSVigorChangeALLProducts"] = {Lock = true},
		["C2GSVigorChangeList"] = {Lock = true},
		["C2GSVigorChangeStart"] = {Lock = true},
		["C2GSVigorChangeItemStatus"] = {Lock = true},
		["C2GSBuyGrid"] = {Lock = true},
		["C2GSVigorChangeProduct"] = {Lock = true},
		["C2GSChangeItemToVigor"] = {Lock = true},		
	},
	["shop"] = {
		["C2GSBuyGood"] = {Lock = true, Tip = "购买物品中，请稍候...", ResumeDelay = 10},
		["C2GSEnterShop"] = {Lock = true},
	}
}
