CPartnerCtrl = require "logic.partner.CPartnerCtrl"

CPartnerMainView = require "logic.partner.CPartnerMainView"
CPartnerAttributePart = require "logic.partner.CPartnerAttributePart"
CPartnerListNodeBox = require "logic.partner.CPartnerListNodeBox"
CPartnerEquipBox = require "logic.partner.CPartnerEquipBox"
CPartnerBox = require "logic.partner.CPartnerBox"
CPartnerSkillInfoBox = require "logic.partner.CPartnerSkillInfoBox"
CPartnerCultureSuccessBox = require "logic.partner.CPartnerCultureSuccessBox"
CPartnerFormationMemberBox = require "logic.partner.CPartnerFormationMemberBox"
CPartnerFormationBox = require "logic.partner.CPartnerFormationBox"
CPartnerFormationPart = require "logic.partner.CPartnerFormationPart"

CPartnerLinkView = require "logic.partner.CPartnerLinkView"
CPartnerCultureBox = require "logic.partner.CPartnerCultureBox"
CPartnerSkillListBox = require "logic.partner.CPartnerSkillListBox"
CPartnerAttrBox = require "logic.partner.CPartnerAttrBox"
CPartnerAddExpBox = require "logic.partner.CPartnerAddExpBox"
CPartnerProtectSkillBox = require "logic.partner.CPartnerProtectSkillBox"
CPartnerUpgradeBox = require "logic.partner.CPartnerUpgradeBox"
CPartnerEquipTipsView = require "logic.partner.CPartnerEquipTipsView"
CPartnerEquipUpgradeView = require "logic.partner.CPartnerEquipUpgradeView"