--c#导出的的类型
module(..., package.seeall)
--System
-- String = typeof(System.String)
-- Int = typeof(System.Int32)

--UnityEngine
Camera = typeof(UnityEngine.Camera)
BoxCollider = typeof(UnityEngine.BoxCollider)
Animator = typeof(UnityEngine.Animator)
AnimatorClipInfo = typeof(UnityEngine.AnimatorClipInfo)
AnimatorOverrideController = typeof(UnityEngine.AnimatorOverrideController)
AnimationClip = typeof(UnityEngine.AnimationClip)
CapsuleCollider = typeof(UnityEngine.CapsuleCollider)
SkinnedMeshRenderer = typeof(UnityEngine.SkinnedMeshRenderer)
AudioSource = typeof(UnityEngine.AudioSource)
AudioClip = typeof(UnityEngine.AudioClip)
Renderer = typeof(UnityEngine.Renderer)
MeshRenderer = typeof(UnityEngine.MeshRenderer)
Material = typeof(UnityEngine.Material)
Texture2D = typeof(UnityEngine.Texture2D)
Shader = typeof(UnityEngine.Shader)
ParticleSystem = typeof(UnityEngine.ParticleSystem)

--NGUI
UIRect = typeof(NGUI.UIRect)
UIWidget = typeof(NGUI.UIWidget)
UIButton = typeof(NGUI.UIButton)
UIButtonScale = typeof(NGUI.UIButtonScale)
UIButtonColor = typeof(NGUI.UIButtonColor)
UIGrid = typeof(NGUI.UIGrid)
UIInput = typeof(NGUI.UIInput)
UIPanel = typeof(NGUI.UIPanel)
UIPopupList = typeof(NGUI.UIPopupList)
UIScrollView = typeof(NGUI.UIScrollView)
UISlider = typeof(NGUI.UISlider)
UITable = typeof(NGUI.UITable)
UICamera = typeof(NGUI.UICamera)
UIRoot = typeof(NGUI.UIRoot)
UIAtlas = typeof(NGUI.UIAtlas)
UIRect = typeof(NGUI.UIRect)
UICenterOnChild = typeof(NGUI.UICenterOnChild)
UILabel = typeof(NGUI.UILabel)
UIDragScrollView = typeof(NGUI.UIDragScrollView)
UIToggle = typeof(NGUI.UIToggle)
UISprite = typeof(NGUI.UISprite)
UISpriteAnimation = typeof(NGUI.UISpriteAnimation)
UIAnchor = typeof(NGUI.UIAnchor)
UITextList = typeof(NGUI.UITextList)
UITweener = typeof(NGUI. UITweener)
UITexture = typeof(NGUI.UITexture)
TweenHeight = typeof(NGUI.TweenHeight)
TweenWidth = typeof(NGUI.TweenWidth)
TweenPosition = typeof(NGUI.TweenPosition)
TweenRotation = typeof(NGUI.TweenRotation)
TweenAlpha = typeof(NGUI.TweenAlpha)
TweenScale = typeof(NGUI.TweenScale)
TweenColor = typeof(NGUI.TweenColor)
SpringPanel = typeof(NGUI.SpringPanel)
TypewriterEffect = typeof(NGUI.TypewriterEffect)
SpringPanel = typeof(NGUI.SpringPanel)

--C_api
GameObjectContainer = typeof(C_api.GameObjectContainer)
UIEventHandler = typeof(C_api.UIEventHandler)
HudHandler = typeof(C_api.Hud)
UIFollowTarget = typeof(C_api.UIFollowTarget)
Map2D = typeof(C_api.Map2D)
Map3D = typeof(C_api.Map3D)
Map2DCamera = typeof(C_api.Map2DCamera)
Map2DWalker = typeof(C_api.Map2DWalker)
Map3DWalker = typeof(C_api.Map3DWalker)
EmojiAnimationController = typeof(C_api.EmojiAnimationController)
UILabelHUD = typeof(C_api.UILabelHUD)
SPSDK = typeof(C_api.SPSDK)
UIEffectRenderQueue = typeof(C_api.UIEffectRenderQueue)
AnimEffect = typeof(C_api.AnimEffect)
AttachCameraHandler = typeof(C_api.AttachCameraHandler)
DataContainer = typeof(C_api.DataContainer)
ParticleAndAnimation = typeof(C_api.ParticleAndAnimation)
LogMgr = typeof(C_api.LogMgr)
HideMapWalker = typeof(C_api.HideMapWalker)
ShotHelper = typeof(C_api.ShotHelper)
XinGeSdk = typeof(C_api.XinGeSdk)
HolePaint = typeof(C_api.HolePaint)
PayManager = typeof(C_api.PayManager)
AMapLocationSdk = typeof(C_api.AMapLocationSdk)
SPSdkManager = typeof(C_api.SPSdkManager)
UniWebView = typeof(C_api.UniWebView)

--CameraPath3
CameraPath = typeof(CameraPath3.CameraPath)
CameraPathAnimator = typeof(CameraPath3.CameraPathAnimator)
CameraPathControlPoint = typeof(CameraPath3.CameraPathControlPoint)

--GamePlot
CameraEntity = typeof(GamePlot.CameraEntity)
PlotEntity = typeof(GamePlot.PlotEntity)

