CContAccumView = require "logic.continuousactivity.CContAccumView"
CContActivityCtrl = require "logic.continuousactivity.CContActivityCtrl"
CContChargePage = require "logic.continuousactivity.CContChargePage"
CContDayBox = require "logic.continuousactivity.CContDayBox"
CContRewardsPart = require "logic.continuousactivity.CContRewardsPart"
CSelectRewardBox = require "logic.continuousactivity.CSelectRewardBox"
CSelectRewardsPart = require "logic.continuousactivity.CSelectRewardsPart"
CContConsumePage = require "logic.continuousactivity.CContConsumePage"