module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={
			args={action_name=[[attack1]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0,
		},
		[2]={
			args={
				alive_time=1.2,
				begin_pos={base_pos=[[atk]],depth=3,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_6101_attack1_fly/Prefabs/skill_eff_6101_attack1_fly.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=1.5,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
				move_time=0.45,
			},
			func_name=[[ShootEffect]],
			start_time=0.55,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/feng.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.8,
		},
		[4]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_6101_attack1_fly/Prefabs/skill_eff_6101_attack1_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=1.5,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.9,
		},
		[5]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=0.9,
		},
		[6]={args={},func_name=[[End]],start_time=1.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
