module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[attack1]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.32,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/huifu.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.7,
		},
		[4]={
			args={face_atk=true,hurt_delta=0,play_anim=false,},
			func_name=[[VicHitInfo]],
			start_time=2.1,
		},
		[5]={args={},func_name=[[End]],start_time=2.2,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
