module(...)
--magic editor build
DATA={
	cmds={
		[1]={
			args={
				alive_time=1,
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3201/Prefabs/magic_eff_3201_att.prefab',
				},
				effect_dir_pos={base_pos='atk',depth=0,relative_angle=0,relative_dis=1,},
				effect_pos={base_pos='atk',depth=0,relative_angle=0,relative_dis=0,},
				excutor='vicobj',
			},
			func_name='StandEffect',
			start_time=0.2,
		},
		[2]={
			args={action_name='attack1',excutor='atkobj',},
			func_name='PlayAction',
			start_time=0.2,
		},
		[3]={
			args={
				alive_time=0.6,
				begin_pos={base_pos='atk',depth=0.6,relative_angle=0,relative_dis=1,},
				ease_type='Linear',
				effect={
					flip=false,
					path='Effect/Magic/skill_eff_1711_full/Prefabs/skill_eff_1711_full.prefab',
				},
				end_pos={base_pos='vic',depth=0.6,relative_angle=0,relative_dis=-1,},
				excutor='vicobj',
				move_time=0.6,
			},
			func_name='ShootEffect',
			start_time=0.55,
		},
		[4]={
			args={
				alive_time=0.5,
				begin_pos={base_pos='atk',depth=0.6,relative_angle=0,relative_dis=1,},
				ease_type='Linear',
				effect={
					flip=false,
					path='Effect/Magic/skill_eff_1711_full/Prefabs/skill_eff_1711_full.prefab',
				},
				end_pos={base_pos='vic',depth=0.6,relative_angle=0,relative_dis=-1,},
				excutor='vicobj',
				move_time=0.5,
			},
			func_name='ShootEffect',
			start_time=0.8,
		},
		[5]={args={},func_name='FirstHit',start_time=0.89,},
		[6]={
			args={
				alive_time=1,
				bind_type='pos',
				body_pos='waist',
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3201/Prefabs/magic_eff_3201_hit.prefab',
				},
				excutor='vicobj',
				height=0,
			},
			func_name='BodyEffect',
			start_time=1,
		},
		[7]={args={face_atk=true,hurt_delta=0,},func_name='VicHitInfo',start_time=1.05,},
		[8]={
			args={
				alive_time=1,
				bind_type='pos',
				body_pos='waist',
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3201/Prefabs/magic_eff_3201_hit.prefab',
				},
				excutor='vicobj',
				height=0,
			},
			func_name='BodyEffect',
			start_time=1.15,
		},
		[9]={args={face_atk=true,hurt_delta=0,},func_name='VicHitInfo',start_time=1.2,},
		[10]={args={},func_name='LastHit',start_time=1.5,},
		[11]={args={},func_name='End',start_time=2.2,},
	},
	first_hit_time=0.89,
	group_cmds={},
	last_hit_time=1.5,
	pre_load_res={},
	run_env='war',
	type=1,
}
