module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={sound_path={soundpath=[[Audio/Sound/War/dao.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.4,
		},
		[3]={
			args={action_name=[[magic]],bak_action_name=[[nil]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.5,
		},
		[4]={
			args={
				alive_time=1.1,
				effect={
					flip=false,
					path=[[Effect/Magic/skill_eff_1106_hit/Prefabs/skill_eff_1106_hit.prefab]],
				},
				effect_cnt=[[one]],
				effect_dir_pos={base_pos=[[empty]],depth=0,relative_angle=0,relative_dis=0,},
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.2,
		},
		[5]={args={},func_name=[[End]],start_time=3,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=false,
}
