module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[attack1]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.51,
		},
		[3]={
			args={
				alive_time=1.75,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_132_hit/Prefabs/skill_eff_132_fly.prefab]],
					preload=false,
				},
				excutor=[[atkobj]],
				height=0.15,
			},
			func_name=[[BodyEffect]],
			start_time=0.61,
		},
		[4]={
			args={sound_path={soundpath=[[Audio/Sound/War/syfs1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.7,
		},
		[5]={
			args={
				alive_time=1,
				begin_pos={base_pos=[[atk]],depth=0.7,relative_angle=0,relative_dis=-0.5,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_132_hit/Prefabs/skill_eff_132_fly2.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0.7,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
				move_time=0.35,
			},
			func_name=[[ShootEffect]],
			start_time=0.81,
		},
		[6]={
			args={sound_path={soundpath=[[Audio/Sound/War/syfs2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1,
		},
		[7]={
			args={
				alive_time=1.75,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_132_hit/Prefabs/skill_eff_132_hit.prefab]],
					preload=false,
				},
				excutor=[[vicobj]],
				height=0.15,
			},
			func_name=[[BodyEffect]],
			start_time=1.25,
		},
		[8]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
				shot=true,
			},
			func_name=[[VicHitInfo]],
			start_time=1.3,
		},
		[9]={args={},func_name=[[End]],start_time=2,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
