module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_137_att/Prefabs/Skill_eff_137_att.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[atk]],depth=0.75,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=0,
		},
		[3]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.45,
		},
		[4]={
			args={sound_path={soundpath=[[Audio/Sound/War/fyld1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.3,
		},
		[5]={
			args={
				alive_time=2,
				begin_pos={base_pos=[[atk]],depth=1,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_140_hit/Prefabs/skill_eff_140_fly.prefab]],
				},
				end_pos={base_pos=[[atk]],depth=7,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
				move_time=0.3,
			},
			func_name=[[ShootEffect]],
			start_time=1.3,
		},
		[6]={
			args={
				alive_time=2,
				begin_pos={base_pos=[[vic_team_center]],depth=7,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[OutSine]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_140_hit/Prefabs/skill_eff_140_fly.prefab]],
				},
				end_pos={base_pos=[[vic_team_center]],depth=3,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
				move_time=0.5,
			},
			func_name=[[ShootEffect]],
			start_time=1.9,
		},
		[7]={
			args={
				alive_time=3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_140_hit/Prefabs/Skill_eff_140_att.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=3,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=2.2,
		},
		[8]={
			args={sound_path={soundpath=[[Audio/Sound/War/fyld2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=2.4,
		},
		[9]={
			args={
				alive_time=3.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_137_hit/Prefabs/Skill_eff_137_full.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic_team_center]],depth=0.5,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=2.7,
		},
		[10]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=3.2,
		},
		[11]={
			args={
				alive_time=1.4,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_137_hit/Prefabs/Skill_eff_137_hit.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=3.2,
		},
		[12]={
			args={shake_dis=0.035,shake_rate=15,shake_time=0.2,},
			func_name=[[ShakeScreen]],
			start_time=3.45,
		},
		[13]={
			args={
				alive_time=0.5,
				ease_hide_time=0,
				ease_show_time=0,
				excutor=[[vicobjs]],
				mat_path=[[Material/effect_Fresnel_Blue.mat]],
			},
			func_name=[[ActorMaterial]],
			start_time=3.5,
		},
		[14]={args={},func_name=[[End]],start_time=3.6,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
