module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[attack4]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.2,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/mh1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.75,
		},
		[4]={
			args={
				alive_time=2,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_145_hit/Prefabs/skill_eff_145_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0.85,
		},
		[5]={
			args={excutor=[[vicobj]],face_to=[[lerp_pos]],h_dis=2070,time=1.18,v_dis=0,},
			func_name=[[FaceTo]],
			start_time=1,
		},
		[6]={
			args={sound_path={soundpath=[[Audio/Sound/War/mh2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.5,
		},
		[7]={
			args={
				consider_hight=false,
				damage_follow=false,
				face_atk=true,
				hurt_delta=0,
				play_anim=false,
			},
			func_name=[[VicHitInfo]],
			start_time=2,
		},
		[8]={
			args={excutor=[[vicobj]],face_to=[[default]],time=0.1,},
			func_name=[[FaceTo]],
			start_time=2.2,
		},
		[9]={args={},func_name=[[End]],start_time=2.3,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
