module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.05,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/sbdl.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.35,
		},
		[4]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_111_full/Prefabs/skill_eff_111_full.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.5,
		},
		[5]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_yellow.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0.7,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			editor_is_ban=false,
			func_name=[[StandEffect]],
			start_time=0.7,
		},
		[6]={
			args={face_atk=false,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=0.7,
		},
		[7]={
			args={
				alive_time=0.3,
				excutor=[[vicobjs]],
				mat_path=[[Material/effect_Fresnel_yellow01.mat]],
			},
			func_name=[[ActorMaterial]],
			start_time=0.7,
		},
		[8]={
			args={shake_dis=0.05,shake_rate=10,shake_time=0.3,},
			func_name=[[ShakeScreen]],
			start_time=0.7,
		},
		[9]={
			args={shake_dis=0.015,shake_rate=30,shake_time=0.3,},
			func_name=[[ShakeScreen]],
			start_time=1.3,
		},
		[10]={args={},func_name=[[End]],start_time=1.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
