module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.32,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/huifu.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.9,
		},
		[4]={
			args={
				alive_time=2.5,
				bind_type=[[pos]],
				body_pos=[[head]],
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_104_att/Prefabs/skill_eff_104_att.prefab]],
				},
				excutor=[[atkobj]],
				height=0.5,
			},
			func_name=[[BodyEffect]],
			start_time=0.9,
		},
		[5]={args={},func_name=[[End]],start_time=1.9,},
		[6]={
			args={face_atk=false,hurt_delta=0,play_anim=false,},
			func_name=[[VicHitInfo]],
			start_time=2.5,
		},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
