module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.1,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/jtbf1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.5,
		},
		[4]={
			args={
				alive_time=2,
				begin_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_135_hit/Prefabs/skill_eff_135_hit.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=3,},
				excutor=[[vicobj]],
				move_time=0.5,
			},
			func_name=[[ShootEffect]],
			start_time=0.5,
		},
		[5]={
			args={
				alive_time=2,
				begin_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=3,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_135_hit/Prefabs/skill_eff_135_hit.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
				move_time=0.35,
			},
			func_name=[[ShootEffect]],
			start_time=1.4,
		},
		[6]={
			args={sound_path={soundpath=[[Audio/Sound/War/jtbf2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.8,
		},
		[7]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=1.9,
		},
		[8]={args={},func_name=[[End]],start_time=2.4,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
