module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=1.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[magic]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.1,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/qjp1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.1,
		},
		[4]={
			args={
				alive_time=2,
				bind_type=[[empty]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_204_hit/Prefabs/Skill_eff_204_mag.prefab]],
					preload=false,
				},
				excutor=[[atkobj]],
				height=1.2,
			},
			func_name=[[BodyEffect]],
			start_time=0.25,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/qjp2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1,
		},
		[6]={
			args={
				alive_time=1,
				begin_pos={base_pos=[[atk]],depth=2,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_204_hit/Prefabs/Skill_eff_204_hit.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0.7,relative_angle=-15,relative_dis=18,},
				excutor=[[atkobj]],
				move_time=0.85,
			},
			func_name=[[ShootEffect]],
			start_time=1.2,
		},
		[7]={
			args={
				alive_time=0.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_yellow.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0.8,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=1.3,
		},
		[8]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=1.3,
		},
		[9]={args={},func_name=[[End]],start_time=2,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
