module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.2,
		},
		[3]={
			args={sound_path={soundpath=[[Audio/Sound/War/gong.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.4,
		},
		[4]={
			args={
				alive_time=1.1,
				begin_pos={base_pos=[[atk]],depth=1,relative_angle=0,relative_dis=0,},
				delay_time=0,
				ease_type=[[Unset]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_105_hit/Prefabs/Skill_eff_105_fly.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic_team_center]],depth=-0.3,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
				move_time=1,
			},
			func_name=[[ShootEffect]],
			start_time=0.6,
		},
		[5]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_105_hit/Prefabs/Skill_eff_105_full.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1,
		},
		[6]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=1.2,
		},
		[7]={
			args={sound_path={soundpath=[[Audio/Sound/War/baozha.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.2,
		},
		[8]={args={},func_name=[[End]],start_time=2,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
