module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={
			args={action_name=[[attack2]],bak_action_name=[[attack5]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0,
		},
		[2]={
			args={
				alive_time=0.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_215_att/Prefabs/skill_eff_215_att4.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.4,
		},
		[3]={
			args={
				alive_time=0.35,
				begin_pos={base_pos=[[atk]],depth=0.7,relative_angle=0,relative_dis=1,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_215_att/Prefabs/skill_eff_215_fly.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0.7,relative_angle=0,relative_dis=0.5,},
				excutor=[[vicobj]],
				move_time=0.35,
			},
			func_name=[[ShootEffect]],
			start_time=0.5,
		},
		[4]={args={},func_name=[[End]],start_time=0.6,},
		[5]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
				shot=true,
			},
			func_name=[[VicHitInfo]],
			start_time=0.75,
		},
		[6]={
			args={
				alive_time=0.15,
				ease_hide_time=0,
				ease_show_time=0.05,
				excutor=[[vicobj]],
				mat_path=[[Material/effect_Fresnel_Ble_red.mat]],
			},
			func_name=[[ActorMaterial]],
			start_time=0.75,
		},
		[7]={
			args={shake_dis=0.05,shake_rate=10,shake_time=0.15,},
			func_name=[[ShakeScreen]],
			start_time=0.75,
		},
		[8]={
			args={
				alive_time=0.5,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_101_hit/Prefabs/Skill_eff_101_hit.prefab]],
					preload=false,
				},
				excutor=[[vicobj]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=0.75,
		},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
