module(...)
--magic editor build
DATA={
	cmds={
		[1]={
			args={
				action_name='runWar',
				action_time=0.5,
				end_frame=19,
				excutor='atkobj',
				start_frame=0,
			},
			func_name='PlayAction',
			start_time=0,
		},
		[2]={
			args={
				begin_type='current',
				calc_face=true,
				ease_type='Linear',
				end_relative={base_pos='vic',depth=0,relative_angle=0,relative_dis=1.2,},
				end_type='end_relative',
				excutor='atkobj',
				move_time=0.35,
				move_type='line',
			},
			func_name='Move',
			start_time=0.15,
		},
		[3]={
			args={
				alive_time=0.84,
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3301/Prefabs/magic_eff_3301_att.prefab',
				},
				effect_dir_pos={base_pos='vic',depth=0,relative_angle=0,relative_dis=-1,},
				effect_pos={base_pos='vic',depth=0,relative_angle=0,relative_dis=1,},
				excutor='vicobj',
			},
			func_name='StandEffect',
			start_time=0.5,
		},
		[4]={
			args={action_name='attack1',excutor='atkobj',},
			func_name='PlayAction',
			start_time=0.5,
		},
		[5]={
			args={
				alive_time=0.5,
				bind_type='pos',
				body_pos='waist',
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3301/Prefabs/magic_eff_3301_hit.prefab',
				},
				excutor='vicobj',
				height=0,
			},
			func_name='BodyEffect',
			start_time=0.65,
		},
		[6]={args={face_atk=true,hurt_delta=0,},func_name='VicHitInfo',start_time=0.68,},
		[7]={args={},func_name='FirstHit',start_time=0.68,},
		[8]={
			args={
				alive_time=0.5,
				bind_type='pos',
				body_pos='waist',
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3301/Prefabs/magic_eff_3301_hit.prefab',
				},
				excutor='vicobj',
				height=0,
			},
			func_name='BodyEffect',
			start_time=1.05,
		},
		[9]={args={face_atk=true,hurt_delta=0,},func_name='VicHitInfo',start_time=1.07,},
		[10]={args={},func_name='LastHit',start_time=1.07,},
		[11]={args={},func_name='End',start_time=1.35,},
	},
	first_hit_time=0.68,
	group_cmds={},
	last_hit_time=1.07,
	pre_load_res={},
	run_env='war',
	type=1,
}
