module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={sound_path={soundpath=[[Audio/Sound/War/dianliu.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.3,
		},
		[3]={
			args={action_name=[[attack2]],excutor=[[atkobj]],},
			editor_is_ban=false,
			func_name=[[PlayAction]],
			start_time=0.5,
		},
		[4]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_149_att/Prefabs/skill_eff_149_att.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.8,
		},
		[5]={
			args={
				begin_type=[[current]],
				calc_face=true,
				ease_type=[[Linear]],
				end_relative={base_pos=[[vic_team_center]],depth=0,relative_angle=0,relative_dis=1,},
				end_type=[[end_relative]],
				excutor=[[atkobj]],
				jump_num=1,
				jump_power=3,
				look_at_pos=true,
				move_time=0.5,
				move_type=[[jump]],
			},
			func_name=[[Move]],
			start_time=1.55,
		},
		[6]={
			args={sound_path={soundpath=[[Audio/Sound/War/dilie.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.8,
		},
		[7]={
			args={
				alive_time=2,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_149_hit/Prefabs/skill_eff_149_hit.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.9,
		},
		[8]={
			args={shake_dis=0.085,shake_rate=15,shake_time=0.2,},
			func_name=[[ShakeScreen]],
			start_time=2,
		},
		[9]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=2,
		},
		[10]={
			args={
				alive_time=0.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0.7,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=2,
		},
		[11]={args={},func_name=[[End]],start_time=2.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
