module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				alive_time=2,
				effect={
					is_cached=true,
					path=[[Effect/Magic/Skill_eff_116_hit/Prefabs/Skill_eff_116_hit.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.2,
		},
		[3]={
			args={
				begin_type=[[current]],
				calc_face=true,
				ease_type=[[Linear]],
				end_relative={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=1,},
				end_type=[[end_relative]],
				excutor=[[atkobj]],
				look_at_pos=true,
				move_time=0.3,
				move_type=[[line]],
			},
			func_name=[[Move]],
			start_time=0.4,
		},
		[4]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.45,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/dao.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.8,
		},
		[6]={args={face_atk=true,hurt_delta=0,},func_name=[[VicHitInfo]],start_time=0.9,},
		[7]={args={},func_name=[[End]],start_time=1.4,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
