module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				alive_time=3.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_167_full/Prefabs/Skill_eff_167_full.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0,
		},
		[3]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0,
		},
		[4]={
			args={
				alive_time=0.5,
				ease_hide_time=0.6,
				ease_show_time=0.35,
				excutor=[[vicobjs]],
				mat_path=[[Material/effect_Fresnel_red_blend02.mat]],
			},
			editor_is_ban=false,
			func_name=[[ActorMaterial]],
			start_time=0.2,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/syfs2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.2,
		},
		[6]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_165_hit/Prefabs/Skill_eff_165_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.5,
		},
		[7]={
			args={sound_path={soundpath=[[Audio/Sound/War/lh2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.7,
		},
		[8]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=false,
				hurt_delta=0,
				play_anim=false,
			},
			func_name=[[VicHitInfo]],
			start_time=0.8,
		},
		[9]={args={},func_name=[[End]],start_time=3.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
