module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				begin_type=[[current]],
				calc_face=false,
				ease_type=[[Unset]],
				end_relative={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=1.5,},
				end_type=[[end_relative]],
				excutor=[[atkobj]],
				look_at_pos=false,
				move_time=0.4,
				move_type=[[line]],
			},
			func_name=[[Move]],
			start_time=0.4,
		},
		[3]={
			args={action_name=[[run]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.4,
		},
		[4]={
			args={sound_path={soundpath=[[Audio/Sound/War/spl1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.4,
		},
		[5]={
			args={action_name=[[attack3]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.5,
		},
		[6]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_154_hit/Prefabs/skill_eff_154_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.95,
		},
		[7]={
			args={sound_path={soundpath=[[Audio/Sound/War/spl2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.95,
		},
		[8]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=1.15,
		},
		[9]={args={},func_name=[[End]],start_time=1.2,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
