module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={
			args={alive_time=0.5,shot=true,show=true,},
			editor_is_ban=false,
			func_name=[[Name]],
			start_time=0,
		},
		[2]={
			args={sound_path={soundpath=[[Audio/Sound/War/jgfm1.ogg]],},},
			editor_is_ban=false,
			func_name=[[PlaySound]],
			start_time=0,
		},
		[3]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_123_att/Prefabs/skill_eff_123_att.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.3,
		},
		[4]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.3,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/jgfm2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.8,
		},
		[6]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_123_full/Prefabs/skill_eff_123_full_02.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0.8,
		},
		[7]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=0.8,
		},
		[8]={
			args={shake_dis=0.4,shake_rate=1,shake_time=0.2,},
			func_name=[[ShakeScreen]],
			start_time=0.85,
		},
		[9]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_yellow.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0.45,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0.96,
		},
		[10]={
			args={
				alive_time=1.35,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_123_full/Prefabs/skill_eff_123_full_01.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0.96,
		},
		[11]={args={},func_name=[[End]],start_time=1.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
