module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={sound_path={soundpath=[[Audio/Sound/War/lstx.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.5,
		},
		[3]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.5,
		},
		[4]={
			args={
				alive_time=0.8,
				begin_pos={base_pos=[[atk]],depth=1.9,relative_angle=0,relative_dis=1,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_2302_attack1_fly/Prefabs/skill_eff_2302_attack1_fly.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=-53,relative_dis=3.7,},
				excutor=[[vicobj]],
				move_time=0.25,
			},
			func_name=[[ShootEffect]],
			start_time=1.2,
		},
		[5]={
			args={
				alive_time=0.8,
				begin_pos={base_pos=[[atk]],depth=1.75,relative_angle=0,relative_dis=1,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_2302_attack1_fly/Prefabs/skill_eff_2302_attack1_fly.prefab]],
				},
				end_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=40,relative_dis=4.25,},
				excutor=[[vicobj]],
				move_time=0.25,
			},
			func_name=[[ShootEffect]],
			start_time=1.2,
		},
		[6]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_green.prefab]],
					preload=false,
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=-53,relative_dis=3.7,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.35,
		},
		[7]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_green.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=40,relative_dis=4.25,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.35,
		},
		[8]={
			args={
				alive_time=3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_143_full/Prefabs/skill_eff_143_full.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=130,relative_dis=-2.75,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.4,
		},
		[9]={
			args={
				alive_time=3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_143_full/Prefabs/skill_eff_143_full2.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic_team_center]],depth=0,relative_angle=55,relative_dis=3.25,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.4,
		},
		[10]={
			args={
				alive_time=0.25,
				ease_hide_time=0.35,
				ease_show_time=0.1,
				excutor=[[vicobjs]],
				mat_path=[[Material/effect_Fresnel_Green01.mat]],
			},
			func_name=[[ActorMaterial]],
			start_time=2.8,
		},
		[11]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=2.8,
		},
		[12]={
			args={
				alive_time=0.5,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit.prefab]],
				},
				excutor=[[vicobjs]],
				height=0.15,
			},
			func_name=[[BodyEffect]],
			start_time=2.8,
		},
		[13]={args={},func_name=[[End]],start_time=3,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
