module(...)
--magic editor build
DATA={
	cmds={
		[1]={
			args={action_name='attack2',excutor='atkobj',},
			func_name='PlayAction',
			start_time=0,
		},
		[2]={
			args={
				alive_time=1,
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3302/Prefabs/magic_eff_3302_att.prefab',
				},
				effect_dir_pos={base_pos='atk',depth=0,relative_angle=0,relative_dis=1,},
				effect_pos={base_pos='atk',depth=0,relative_angle=0,relative_dis=0,},
				excutor='vicobj',
			},
			func_name='StandEffect',
			start_time=0,
		},
		[3]={args={},func_name='LastHit',start_time=0,},
		[4]={
			args={
				alive_time=2,
				effect={
					flip=false,
					path='Effect/Magic/magic_eff_3302/Prefabs/magic_eff_3302_hit.prefab',
				},
				effect_dir_pos={base_pos='vic',depth=0,relative_angle=0,relative_dis=1,},
				effect_pos={base_pos='vic',depth=0,relative_angle=0,relative_dis=0,},
				excutor='vicobjs',
			},
			func_name='StandEffect',
			start_time=0.55,
		},
		[5]={args={},func_name='FirstHit',start_time=0.65,},
		[6]={args={face_atk=true,hurt_delta=0,},func_name='VicHitInfo',start_time=0.7,},
		[7]={args={},func_name='End',start_time=0.75,},
	},
	first_hit_time=0.65,
	group_cmds={},
	last_hit_time=0,
	pre_load_res={},
	run_env='war',
	type=1,
}
