module(...)
--magic editor build
DATA={
	atk_stophit=false,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				excutor=[[atkobj]],
				face_to=[[fixed_pos]],
				pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				time=0.2,
			},
			editor_is_ban=false,
			func_name=[[FaceTo]],
			start_time=0,
		},
		[3]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_199_fly/Prefabs/skill_eff_199_fly1.prefab]],
				},
				effect_dir_type=[[relative]],
				effect_pos={base_pos=[[atk]],depth=1.2,relative_angle=90,relative_dis=0.7,},
				excutor=[[atkobj]],
				relative_dir={base_pos=[[vic]],depth=0.75,relative_angle=0,relative_dis=0,},
			},
			func_name=[[StandEffect]],
			start_time=0.3,
		},
		[4]={
			args={
				alive_time=0.5,
				begin_pos={base_pos=[[atk]],depth=1.2,relative_angle=90,relative_dis=0.7,},
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_199_fly/Prefabs/skill_eff_199_fly2.prefab]],
				},
				end_pos={base_pos=[[vic]],depth=0.75,relative_angle=0,relative_dis=-0.35,},
				excutor=[[vicobjs]],
				move_time=0.5,
			},
			func_name=[[ShootEffect]],
			start_time=0.4,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/jian.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.7,
		},
		[6]={
			args={
				alive_time=1,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_100_hit/Prefabs/skill_eff_100_hit_blue.prefab]],
				},
				excutor=[[vicobj]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=0.8,
		},
		[7]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			editor_is_ban=false,
			func_name=[[VicHitInfo]],
			start_time=0.8,
		},
		[8]={
			args={excutor=[[atkobj]],face_to=[[default]],time=0.2,},
			editor_is_ban=false,
			func_name=[[FaceTo]],
			start_time=1,
		},
		[9]={args={},func_name=[[End]],start_time=1.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
