module(...)
--magic editor build
DATA={
	atk_stophit=false,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={sound_path={soundpath=[[Audio/Sound/War/xssp.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.4,
		},
		[3]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_136_att/Prefabs/skill_eff_136_att.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.4,
		},
		[4]={
			args={alive_time=2,color={a=0,b=255,g=255,r=255,},excutor=[[atkobj]],fade_time=0.35,},
			func_name=[[ActorColor]],
			start_time=1,
		},
		[5]={
			args={
				alive_time=1.5,
				effect={
					is_cached=true,
					path=[[Effect/Magic/skill_eff_136_1_att/Prefabs/skill_eff_136_1_att.prefab]],
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[atk]],depth=-0.5,relative_angle=0,relative_dis=0,},
				excutor=[[atkobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.5,
		},
		[6]={
			args={
				alive_time=1.77,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_136_hit/Prefabs/skill_eff_136_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=2.3,
		},
		[7]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=true,
			},
			func_name=[[VicHitInfo]],
			start_time=2.5,
		},
		[8]={args={},func_name=[[End]],start_time=3.6,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
