module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.4,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				begin_type=[[current]],
				calc_face=true,
				ease_type=[[InFlash]],
				end_relative={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=2,},
				end_type=[[end_relative]],
				excutor=[[atkobj]],
				look_at_pos=true,
				move_time=0.3,
				move_type=[[line]],
			},
			func_name=[[Move]],
			start_time=0.35,
		},
		[3]={
			args={action_name=[[run]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.35,
		},
		[4]={
			args={action_name=[[attack2]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.5,
		},
		[5]={
			args={
				alive_time=0.5,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_196_full/Prefabs/Skill_eff_196_full.prefab]],
					preload=false,
				},
				effect_dir_type=[[backward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=2.5,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.78,
		},
		[6]={
			args={
				alive_time=1.5,
				begin_pos={base_pos=[[vic]],depth=0.55,relative_angle=0,relative_dis=2,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=false,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_196_full/Prefabs/Skill_eff_196_fly.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0.55,relative_angle=0,relative_dis=-13,},
				excutor=[[vicobj]],
				move_time=1.5,
			},
			func_name=[[ShootEffect]],
			start_time=0.85,
		},
		[7]={
			args={sound_path={soundpath=[[Audio/Sound/War/dao.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.9,
		},
		[8]={
			args={
				alive_time=1.2,
				bind_type=[[pos]],
				body_pos=[[waist]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_196_full/Prefabs/Skill_eff_196_hit.prefab]],
					preload=false,
				},
				excutor=[[vicobj]],
				height=0,
			},
			func_name=[[BodyEffect]],
			start_time=0.92,
		},
		[9]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=0.92,
		},
		[10]={
			args={sound_path={soundpath=[[Audio/Sound/War/quanji.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1,
		},
		[11]={args={},func_name=[[End]],start_time=1.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
