module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={},func_name=[[MagcAnimStart]],start_time=0,},
		[2]={
			args={action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.3,
		},
		[3]={
			args={
				consider_hight=false,
				damage_follow=true,
				face_atk=true,
				hurt_delta=0,
				play_anim=false,
				shot=true,
			},
			func_name=[[VicHitInfo]],
			start_time=0.6,
		},
		[4]={
			args={
				alive_time=2.3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_217_hit/Prefabs/Skill_eff_217_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobjs]],
			},
			func_name=[[StandEffect]],
			start_time=0.6,
		},
		[5]={args={},func_name=[[MagcAnimEnd]],start_time=0.7,},
		[6]={args={},func_name=[[End]],start_time=2.9,},
	},
	group_cmds={},
	magic_anim_end_time=0.7,
	magic_anim_start_time=0,
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
