module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=1,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={action_name=[[attack4]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.75,
		},
		[3]={
			args={
				excutor=[[atkobj]],
				face_to=[[look_at]],
				pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				time=0.5,
			},
			func_name=[[FaceTo]],
			start_time=0.85,
		},
		[4]={
			args={
				alive_time=1.5,
				begin_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=0,},
				delay_time=0.5,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_152_att/Prefabs/skill_eff_152_att.prefab]],
				},
				end_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=2,},
				excutor=[[vicobj]],
				move_time=0.2,
			},
			editor_is_ban=false,
			func_name=[[ShootEffect]],
			start_time=0.9,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/xycf1.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1,
		},
		[6]={
			args={
				alive_time=0.4,
				begin_pos={base_pos=[[atk]],depth=0,relative_angle=0,relative_dis=-0.5,},
				delay_time=0,
				ease_type=[[Linear]],
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_152_att/Prefabs/skill_eff_152_att_1320.prefab]],
					preload=false,
				},
				end_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0.5,},
				excutor=[[vicobj]],
				move_time=0.4,
			},
			editor_is_ban=false,
			func_name=[[ShootEffect]],
			start_time=1.35,
		},
		[7]={
			args={sound_path={soundpath=[[Audio/Sound/War/xycf2.ogg]],},},
			func_name=[[PlaySound]],
			start_time=1.4,
		},
		[8]={
			args={face_atk=true,hurt_delta=0,play_anim=true,},
			func_name=[[VicHitInfo]],
			start_time=1.45,
		},
		[9]={
			args={
				alive_time=1,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/skill_eff_152_hit/Prefabs/skill_eff_152_hit.prefab]],
					preload=false,
				},
				effect_dir_type=[[forward]],
				effect_pos={base_pos=[[vic]],depth=0.75,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=1.45,
		},
		[10]={
			args={excutor=[[atkobj]],face_to=[[default]],time=0.3,},
			func_name=[[FaceTo]],
			start_time=2,
		},
		[11]={args={},func_name=[[End]],start_time=2.13,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
