module(...)
--magic editor build
DATA={
	atk_stophit=true,
	cmds={
		[1]={args={alive_time=0.5,shot=true,show=true,},func_name=[[Name]],start_time=0,},
		[2]={
			args={
				alive_time=3,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_170_hit/Prefabs/Skill_eff_170_hit.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0,
		},
		[3]={
			args={action_name=[[magic]],bak_action_name=[[attack1]],excutor=[[atkobj]],},
			func_name=[[PlayAction]],
			start_time=0.35,
		},
		[4]={
			args={
				alive_time=1.2,
				effect={
					is_cached=true,
					magic_layer=[[center]],
					path=[[Effect/Magic/Skill_eff_171_full/Prefabs/Skill_eff_171_body.prefab]],
				},
				effect_dir_type=[[empty]],
				effect_pos={base_pos=[[vic]],depth=0,relative_angle=0,relative_dis=0,},
				excutor=[[vicobj]],
			},
			func_name=[[StandEffect]],
			start_time=0.8,
		},
		[5]={
			args={sound_path={soundpath=[[Audio/Sound/War/foyin.ogg]],},},
			func_name=[[PlaySound]],
			start_time=0.8,
		},
		[6]={
			args={face_atk=false,hurt_delta=0,play_anim=false,},
			func_name=[[VicHitInfo]],
			start_time=0.85,
		},
		[7]={
			args={
				alive_time=0.2,
				ease_hide_time=0.8,
				ease_show_time=0.2,
				excutor=[[atkobj]],
				mat_path=[[Material/effect_Fresnel_red.mat]],
			},
			func_name=[[ActorMaterial]],
			start_time=0.88,
		},
		[8]={args={},func_name=[[End]],start_time=2.5,},
	},
	group_cmds={},
	pre_load_res={},
	run_env=[[war]],
	type=1,
	wait_goback=true,
}
