//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SimpleWindowPrefab.
/// </summary>
public partial class SimpleWindowPrefab : BaseView
{
	public UILabel simple_InfoLabel;
	public UIButton simple_OKButton;
	public UILabel simple_OKLabel;
	public UIButton simple_CancelButton;
	public UILabel simple_CancelLabel;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		simple_InfoLabel = root.Find("SimpleWin/simple_InfoLabel").GetComponent<UILabel>();
		simple_OKButton = root.Find("SimpleWin/simple_OKButton").GetComponent<UIButton>();
		simple_OKLabel = root.Find("SimpleWin/simple_OKButton/simple_OKLabel").GetComponent<UILabel>();
		simple_CancelButton = root.Find("SimpleWin/simple_CancelButton").GetComponent<UIButton>();
		simple_CancelLabel = root.Find("SimpleWin/simple_CancelButton/simple_CancelLabel").GetComponent<UILabel>();
	}
}
