//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkBindCodeView.
/// </summary>
public partial class SdkBindCodeView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkBindCodeView.prefab";
	public UIInput AccoutInput;
	public UIButton GetCodeBtn;
	public UIButton BackBtn;
	public UILabel TitleLabel;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		AccoutInput = root.Find("AccoutInput").GetComponent<UIInput>();
		GetCodeBtn = root.Find("GetCodeBtn").GetComponent<UIButton>();
		BackBtn = root.Find("BackBtn").GetComponent<UIButton>();
		TitleLabel = root.Find("TitleBg/TitleLabel").GetComponent<UILabel>();
	}
}
