//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkDeviceNotice.
/// </summary>
public partial class SdkDeviceNotice : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkDeviceNotice.prefab";
	public UIButton LoginButton;
	public UIButton BackBtn;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		LoginButton = root.Find("LoginButton").GetComponent<UIButton>();
		BackBtn = root.Find("BackBtn").GetComponent<UIButton>();
	}
}
