//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkGameCenterView.
/// </summary>
public partial class SdkGameCenterView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkGameCenterView.prefab";
	public UIButton BindBtn;
	public UIButton ModifyPasswordBtn;
	public UIButton ChangeAccountBtn;
	public UIButton ModifyNameBtn;
	public UISprite AvatarIcon;
	public UILabel NameLabel;
	public UILabel UIDLabel;
	public UISprite InfoBgSprite;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		BindBtn = root.Find("BtnGrid/BindBtn").GetComponent<UIButton>();
		ModifyPasswordBtn = root.Find("BtnGrid/ModifyPasswordBtn").GetComponent<UIButton>();
		ChangeAccountBtn = root.Find("BtnGrid/ChangeAccountBtn").GetComponent<UIButton>();
		ModifyNameBtn = root.Find("BtnGrid/ModifyNameBtn").GetComponent<UIButton>();
		AvatarIcon = root.Find("AccountInfo/AvatarIcon").GetComponent<UISprite>();
		NameLabel = root.Find("AccountInfo/NameLabel").GetComponent<UILabel>();
		UIDLabel = root.Find("AccountInfo/UIDLabel").GetComponent<UILabel>();
		InfoBgSprite = root.Find("AccountInfo/bg").GetComponent<UISprite>();
	}
}
