//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkOfficialView.
/// </summary>
public partial class SdkOfficialView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkOfficialView.prefab";
	public UIButton CancelBtn;
	public UIButton CommitBtn;
	public UIInput NameInput;
	public UIInput CardInput;
	public UIButton BackBtn;
	public UIPanel SdkOfficialView_UIPanel;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		CancelBtn = root.Find("CancelBtn").GetComponent<UIButton>();
		CommitBtn = root.Find("CommitBtn").GetComponent<UIButton>();
		NameInput = root.Find("NameGroup/Input").GetComponent<UIInput>();
		CardInput = root.Find("CardGroup/Input").GetComponent<UIInput>();
		BackBtn = root.Find("BackBtn").GetComponent<UIButton>();
	SdkOfficialView_UIPanel = root.GetComponent<UIPanel>();
	}
}
