//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkPayView.
/// </summary>
public partial class SdkPayView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkPayView.prefab";
	public UIButton AliPayLogin_UIButton;
	public UIButton WechatPayLogin_UIButton;
	public UIButton BackBtn_UIButton;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		AliPayLogin_UIButton = root.Find("BtnGrid/AliPayLogin").GetComponent<UIButton>();
		WechatPayLogin_UIButton = root.Find("BtnGrid/WechatPayLogin").GetComponent<UIButton>();
		BackBtn_UIButton = root.Find("BackBtn").GetComponent<UIButton>();
	}
}
