//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkRegisterConfirmView.
/// </summary>
public partial class SdkRegisterConfirmView : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkRegisterConfirmView.prefab";
	public UIInput CodeInput;
	public UIInput PasswordInput;
	public UIInput PasswordInput2;
	public UIButton RegisterBtn;
	public UIButton ReSendBtn;
	public UIButton BackBtn;
	public UILabel SendCodeLbl;

	protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		CodeInput = root.Find("CodeInput").GetComponent<UIInput>();
		PasswordInput = root.Find("PasswordInput").GetComponent<UIInput>();
		PasswordInput2 = root.Find("PasswordInput2").GetComponent<UIInput>();
		RegisterBtn = root.Find("RegisterBtn").GetComponent<UIButton>();
		ReSendBtn = root.Find("ReSendBtn").GetComponent<UIButton>();
		BackBtn = root.Find("BackBtn").GetComponent<UIButton>();
		SendCodeLbl = root.Find("ReSendBtn/Label").GetComponent<UILabel>();
	}
}
