//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SelectLoginView.
/// </summary>
public partial class SdkSelectLoginView : BaseView
{
    public const string NAME = "UI/SdkAcccountPrefabs/SdkSelectLoginView.prefab";
	public UIButton QuickLoginBtn;
	public UIButton PlatformLoginBtn;
	public UIButton QQLoginBtn;
    public UIButton QRLoginBtn;
    public UIGrid BtnGrid;
    public UIButton QuickLoginBtnEx;
    public UIButton PlatformLoginBtnEx;

    protected override void InitElementBinding ()
    {
        var root = this.gameObject.transform;
		QuickLoginBtn = root.Find("BtnGrid/QuickLogin").GetComponent<UIButton>();
		PlatformLoginBtn = root.Find("BtnGrid/PlatformLogin").GetComponent<UIButton>();
		//QQLoginBtn = root.Find("BtnGrid/QQLogin").GetComponent<UIButton>();
        QRLoginBtn = root.Find("BtnGrid/QRLogin").GetComponent<UIButton>();
        BtnGrid = root.Find("BtnGrid").GetComponent<UIGrid>();
        QuickLoginBtnEx = root.Find("QuickLoginEx").GetComponent<UIButton>();
        PlatformLoginBtnEx = root.Find("PlatformLoginEx").GetComponent<UIButton>();
    }
}
