//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SdkToolbar.
/// </summary>
public partial class SdkToolbar : BaseView
{
	public const string NAME = "UI/SdkAcccountPrefabs/SdkToolbar.prefab";
	public GameObject BarGo;
	public UIButton AccountBtn;
	public UIButton BackBtn;
	public UIDragObject IconDragObject;
	public UIEventTrigger IconTrigger;
	public UISprite IconSprite;
	public UIButton BBSBtn_UIButton;

	protected override void InitElementBinding ()
	{
		var root = this.gameObject.transform;
		BarGo = root.Find("Bar").gameObject;
		AccountBtn = root.Find("Bar/AccountBtn").GetComponent<UIButton>();
		BackBtn = root.Find("Bar/BackBtn").GetComponent<UIButton>();
		IconDragObject = root.Find("IconBtn").GetComponent<UIDragObject>();
		IconTrigger = root.Find("IconBtn").GetComponent<UIEventTrigger>();
		IconSprite = root.Find("IconBtn").GetComponent<UISprite>();
		//BBSBtn_UIButton = root.Find("Bar/BBSBtn").GetComponent<UIButton>();
	}
}
