CRedPacketMainView = require "logic.redpacket.CRedPacketMainView"
CRedPacketOrgPart = require "logic.redpacket.CRedPacketOrgPart"
CRedPacketWorldPart = require "logic.redpacket.CRedPacketWorldPart"
CRedPacketSendView = require "logic.redpacket.CRedPacketSendView"
CRedPacketGetView = require "logic.redpacket.CRedPacketGetView"
CRedPacketGetPlayerView = require "logic.redpacket.CRedPacketGetPlayerView"
CRedPacketSelfRecordView = require "logic.redpacket.CRedPacketSelfRecordView"
CRedPacketItemSendView = require "logic.redpacket.CRedPacketItemSendView"
CRedPacketSendSelectView = require "logic.redpacket.CRedPacketSendSelectView"
CRedPacketOrgSysSendView = require "logic.redpacket.CRedPacketOrgSysSendView"
CRedPacketSelectMoneyView = require "logic.redpacket.CRedPacketSelectMoneyView"

CRedPacketCtrl = require "logic.redpacket.CRedPacketCtrl"