CShopCtrl = require "logic.npcshop.CShopCtrl"
CNpcShopMainView = require "logic.npcshop.CNpcShopMainView"
CNpcShopPart= require "logic.npcshop.CNpcShopPart"
CRechargePart = require "logic.npcshop.CRechargePart"
CRechargeItem = require "logic.npcshop.CRechargeItem"
CSummonStorePart = require "logic.npcshop.CSummonStorePart"
CSummonStoreItem = require "logic.npcshop.CSummonStoreItem"
CSummonStoreView = require "logic.npcshop.CSummonStoreView"
CNpcShopItemBox = require "logic.npcshop.CNpcShopItemBox"
CNpcShopViewBase = require "logic.npcshop.CNpcShopViewBase"
CNpcEquipShopView = require "logic.npcshop.CNpcEquipShopView"
CNpcMedicineShopView = require "logic.npcshop.CNpcMedicineShopView"
CNpcGroceryShopView = require "logic.npcshop.CNpcGroceryShopView"
CNpcWeaponShopView = require "logic.npcshop.CNpcWeaponShopView"
CGoldCoinShopPart = require "logic.npcshop.CGoldCoinShopPart"
CGoldGoinShopItemBox = require "logic.npcshop.CGoldGoinShopItemBox"
CRechargeGoldCoinItem = require "logic.npcshop.CRechargeGoldCoinItem"

-- CRebateBox = require "logic.npcshop.CRebateBox"
CChargeRebateBox = require "logic.npcshop.rebate.CChargeRebateBox"
CChargeRebateView = require "logic.npcshop.rebate.CChargeRebateView"

CScoreShopPart = require "logic.npcshop.CScoreShopPart"
CShopPointView = require "logic.npcshop.CShopPointView"