// **********************************************************************
// Copyright (c) 2016 Baoyugame. All rights reserved.
// Author : Xianjian
// Created : 9/30/2016 2:17:58 PM
// Desc	: Auto generated by MarsZ. update this if need.
// **********************************************************************

using UnityEngine;

 /// <summary>
 /// This is the controller class for module GameCenter, use this to control the ui or view , such as it's init , update or dispose.
 /// @Xianjian in 9/30/2016 2:17:58 PM
 /// </summary>
public class SdkGameCenterController : MonoViewController<SdkGameCenterView>
{
    public void RefreshShow()
    {
        var oAccount = SdkAccountModel.Instance.loginAccount;
        if (oAccount == null) return;

        _view.NameLabel.text = string.Format("昵称：{0}", oAccount.loginSeesionDto.nickname);
        _view.UIDLabel.text = string.Format("UID：{0}", oAccount.loginSeesionDto.uid);

        int labelWidth = Mathf.Max(View.NameLabel.width, View.UIDLabel.width);
        View.InfoBgSprite.width = 120 + labelWidth;
    }

    protected override void RegisterEvent()
    {
        EventDelegate.Set(_view.ChangeAccountBtn.onClick, OnChangeAccount);
        EventDelegate.Set(_view.ModifyNameBtn.onClick, OnModifyName);
        EventDelegate.Set(_view.ModifyPasswordBtn.onClick, OnModifyPassword);
        EventDelegate.Set(_view.BindBtn.onClick, OnBindAccount);
    }

    public void OnChangeAccount()
    {
        SdkAccountModel.Instance.ChangeAccount();
    }

    public void OnModifyPassword()
    {
        SdkProxyModule.OpenModifyPassword();
    }

    public void OnModifyName()
    {
        //SdkProxyModule.OpenModule<SdkModifyPasswordController>(SdkModifyPasswordView.NAME);
    }

    public void OnBindAccount()
    {
        SdkProxyModule.OpenBind();
    }
}
