// **********************************************************************
// Copyright (c) 2016 Baoyugame. All rights reserved.
// Author : Xianjian
// Created : 9/30/2016 2:52:39 PM
// Desc	: Auto generated by MarsZ. update this if need.
// **********************************************************************

using UnityEngine;

 /// <summary>
 /// This is the controller class for module ModifyPassword, use this to control the ui or view , such as it's init , update or dispose.
 /// @Xianjian in 9/30/2016 2:52:39 PM
 /// </summary>
public class SdkModifyPasswordController : MonoViewController<SdkModifyPasswordView>
 {
    private bool isUseSystemAccount;
    protected override void InitView()
    {
        string phone = SdkAccountModel.Instance.GetAccountName();
        if (phone.Length == 11)
        {
            View.AccoutInput.validation = UIInput.Validation.None;
            View.AccoutInput.value = "*******" + phone.Substring(7, 4);
            isUseSystemAccount = true;
        }
        else
        {
            View.AccoutInput.validation = UIInput.Validation.Integer;
            isUseSystemAccount = false;
        }

        View.AccoutInput.GetComponent<BoxCollider>().enabled = !isUseSystemAccount;
    }

    protected override void RegisterEvent()
    {
        EventDelegate.Set(_view.BackBtn.onClick, () => { SdkProxyModule.CloseModuleSlow(SdkModifyPasswordView.NAME); });
        EventDelegate.Set(_view.GetCodeBtn.onClick, OnGetCode);
    }

    public void OnGetCode()
    {
        string phone;
        if (!isUseSystemAccount)
        {
            phone = _view.AccoutInput.value;
        }
        else
        {
            phone = SdkAccountModel.Instance.GetAccountName();
        }

        if (!SdkAccountModel.CheckPhone(phone))
        {
            return;
        }

        SdkService.RequestPhoneCode(phone, (code) =>
        {
            if (BaseView.IsViewDestroy(View))
                return;

            if (code == 0)
            {
                var com = SdkProxyModule.OpenModule<SdkModifyPasswordConfirmController>(SdkModifyPasswordConfirmView.NAME);
                com.InitData(phone);
            }
        });
    }
}
